import AppKit
import Foundation

/// File overview:
/// Pure value types for the clipboard history feature: one captured entry, the ring-buffer store, and
/// the capture filter. None of these poll the pasteboard or run timers, so they are fully unit
/// testable. Text-only for now; image clips are a follow-up.

/// One captured clipboard entry.
struct ClipboardItem: Identifiable, Equatable {
    let id: UUID
    let text: String
    let sourceApp: String?
    let capturedAt: Date

    /// A trimmed single-line preview for the picker row.
    var preview: String {
        let firstLine = text.split(whereSeparator: \.isNewline).first.map(String.init) ?? text
        let trimmed = firstLine.trimmingCharacters(in: .whitespaces)
        return trimmed.isEmpty ? text.trimmingCharacters(in: .whitespacesAndNewlines) : trimmed
    }
}

/// A most-recent-first ring buffer of clipboard entries with consecutive-duplicate suppression and a
/// hard capacity. Pure: the service feeds it captured items, and the picker reads `items`/`filtered`.
struct ClipboardHistoryStore {
    private(set) var items: [ClipboardItem] = []
    let capacity: Int

    init(capacity: Int = 15) {
        self.capacity = max(1, capacity)
    }

    mutating func record(_ item: ClipboardItem) {
        // Re-copying existing text moves it to the front rather than duplicating it.
        items.removeAll { $0.text == item.text }
        items.insert(item, at: 0)
        if items.count > capacity {
            items.removeLast(items.count - capacity)
        }
    }

    mutating func clear() {
        items.removeAll()
    }

    /// Items whose text contains `query` (case-insensitive), preserving recency order. An empty query
    /// returns everything.
    func filtered(by query: String) -> [ClipboardItem] {
        let trimmed = query.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty else { return items }
        return items.filter { $0.text.range(of: trimmed, options: .caseInsensitive) != nil }
    }
}

/// Decides whether a pasteboard change should be captured into history, based on its declared types.
/// Skips password-manager and transient content (which set the standard `org.nspasteboard.*`
/// markers) and Cotabby's own synthetic writes.
enum ClipboardCaptureFilter {
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    static func shouldCapture(types: [NSPasteboard.PasteboardType]) -> Bool {
        let blocked: Set<NSPasteboard.PasteboardType> = [
            concealedType, transientType, autoGeneratedType, SyntheticPasteboardMarker.type
        ]
        return !types.contains { blocked.contains($0) }
    }
}
