name: CI
on:
  pull_request:
  push:
    branches: [main, master]
permissions:
  contents: read
jobs:
  quality:
    uses: NERV-es/NERV/.github/workflows/lint-reusable.yml@4d90a48b4ea8370863b30ecd0088a44520dcd6e4 # ci-quality-v1
