name: Typos

permissions:
  contents: read
on:
  pull_request:
  workflow_dispatch:
jobs:
  typos:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Check spelling
        uses: crate-ci/typos@c16dc8f5c6a5a390ad7ad6161a58ec627c4678c0 # v1.27.3
