import AppKit
import XCTest
@testable import Cotabby

/// Tests for the pure clipboard history store (ring buffer, dedup, filter) and the capture filter
/// (privacy markers and Cotabby's own synthetic-write marker).

final class ClipboardHistoryStoreTests: XCTestCase {
    private func item(_ text: String) -> ClipboardItem {
        ClipboardItem(id: UUID(), text: text, sourceApp: nil, capturedAt: Date(timeIntervalSince1970: 0))
    }

    func test_recordAddsMostRecentFirst() {
        var store = ClipboardHistoryStore(capacity: 10)
        store.record(item("a"))
        store.record(item("b"))
        XCTAssertEqual(store.items.map(\.text), ["b", "a"])
    }

    func test_recordDeduplicatesByTextMovingToFront() {
        var store = ClipboardHistoryStore(capacity: 10)
        store.record(item("a"))
        store.record(item("b"))
        store.record(item("a"))
        XCTAssertEqual(store.items.map(\.text), ["a", "b"])
    }

    func test_capacityCapsToMostRecent() {
        var store = ClipboardHistoryStore(capacity: 2)
        store.record(item("a"))
        store.record(item("b"))
        store.record(item("c"))
        XCTAssertEqual(store.items.map(\.text), ["c", "b"])
    }

    func test_filteredBySubstringCaseInsensitive() {
        var store = ClipboardHistoryStore(capacity: 10)
        store.record(item("Hello World"))
        store.record(item("goodbye"))
        XCTAssertEqual(store.filtered(by: "hello").map(\.text), ["Hello World"])
    }

    func test_filteredEmptyQueryReturnsAll() {
        var store = ClipboardHistoryStore(capacity: 10)
        store.record(item("a"))
        store.record(item("b"))
        XCTAssertEqual(store.filtered(by: "  ").map(\.text), ["b", "a"])
    }

    func test_clearEmptiesHistory() {
        var store = ClipboardHistoryStore(capacity: 10)
        store.record(item("a"))
        store.clear()
        XCTAssertTrue(store.items.isEmpty)
    }

    func test_previewIsFirstNonEmptyLineTrimmed() {
        let multiline = ClipboardItem(
            id: UUID(),
            text: "  first line  \n second line ",
            sourceApp: nil,
            capturedAt: Date(timeIntervalSince1970: 0)
        )
        XCTAssertEqual(multiline.preview, "first line")
    }
}

final class ClipboardCaptureFilterTests: XCTestCase {
    func test_capturesPlainText() {
        XCTAssertTrue(ClipboardCaptureFilter.shouldCapture(types: [.string]))
    }

    func test_capturesWhenNoTypes() {
        XCTAssertTrue(ClipboardCaptureFilter.shouldCapture(types: []))
    }

    func test_skipsConcealed() {
        XCTAssertFalse(
            ClipboardCaptureFilter.shouldCapture(types: [.string, ClipboardCaptureFilter.concealedType])
        )
    }

    func test_skipsTransient() {
        XCTAssertFalse(ClipboardCaptureFilter.shouldCapture(types: [ClipboardCaptureFilter.transientType]))
    }

    func test_skipsAutoGenerated() {
        XCTAssertFalse(ClipboardCaptureFilter.shouldCapture(types: [ClipboardCaptureFilter.autoGeneratedType]))
    }

    func test_skipsCotabbySyntheticWrites() {
        XCTAssertFalse(
            ClipboardCaptureFilter.shouldCapture(types: [.string, SyntheticPasteboardMarker.type])
        )
    }
}
